<?php
use Drupal\Core\Url;
use Symfony\Component\HttpFoundation\RedirectResponse;
/**
 * @file
 * Contains mz_chat.module.
 */

function mz_staydirect_form_alter(&$form, &$form_state, $form_id)  {
  
  if ($form_id == 'node_site_form') {
   
  }
}
/**
 * Implements hook_preprocess_HOOK().
 */
function mz_staydirect_preprocess_block(&$variables) {
  if(isset($variables['content']) && isset($variables['content']['#block_content'])){
    global $site_variables ;
    $block_object = $variables['content']['#block_content'];
    $type = $block_object->bundle();
    $service_booking = \Drupal::service('mz_booking.manager');
    $variables['#cache']['max-age'] = 0;
    if($type =='header'){
      $variables['site_variables'] = $site_variables;
    }
  }
}
  
/**
 * Implements hook_preprocess_HOOK() for page templates.
 */
function mz_staydirect_preprocess_page(&$variables) {

  $route = \Drupal::routeMatch()->getRouteObject();
  $is_admin = \Drupal::service('router.admin_context')->isAdminRoute($route);
  global $site_variables ;
  if(!$is_admin && $site_variables  && isset($site_variables["site_theme"])){
      // Check the value of a configuration variable.
      $config = \Drupal::config('mz_staydirect.settings');
      $init = $config->get('init');
      if( $init == 0 ){
   
        // switch themes       
        // $theme = "staydirect_".$site_variables["site_theme"];
        // \Drupal::configFactory()
        //   ->getEditable('system.theme')
        //   ->set('default', $theme)
        //   ->save();

        //   \Drupal::configFactory()->getEditable('mz_staydirect.settings')
        //   ->set('init',1)
        //   ->save();
        //   drupal_flush_all_caches();  
        //   // Redirect to the front page.
        //   $response = new RedirectResponse(Url::fromRoute('<front>')->toString());
        //   $response->send();
      }
  }
}