<?php
use Drupal\Core\Url;
use Symfony\Component\HttpFoundation\RedirectResponse;
/**
 * @file
 * Contains mz_chat.module.
 */

function mz_staydirect_form_alter(&$form, &$form_state, $form_id)  {
  
  if ($form_id == 'node_site_form') {
   
  }
}
/**
 * Implements hook_preprocess_HOOK().
 */
function mz_staydirect_preprocess_block(&$variables) {
  if(isset($variables['content']) && isset($variables['content']['#block_content'])){
    global $site_variables ;
    $block_object = $variables['content']['#block_content'];
    $type = $block_object->bundle();
    $service_booking = \Drupal::service('mz_booking.manager');

    $variables['#cache']['max-age'] = 0;
    if($type =='header'){
      $variables['site_variables'] = $site_variables;
    }
    if($type == "contact"){
    
      $service = \Drupal::service('drupal.helper');
      $params = $service->helper->get_parameter();
      if(isset($params['email']) && isset($params['request_body'])){
          $config = \Drupal::config('mz_staydirect.settings');
          $site_infos = $config->get('site_variables');
          $email = \Drupal::config('system.site')->get('mail');
          if( isset($site_infos["email"])){
            $email = $site_infos["email"];
          }
          
         $status =  $service->helper->send_mail_simple($params['request_body'], $email ,$params['email'],'Send Request ');
         if(  $status ) {
          $message = "Your request is sent successfully...";
          \Drupal::messenger()->addMessage($message);
         }else {
          $message =  "Your request could not be sent...";
          \Drupal::messenger()->addMessage($message,'error');
         }
      }

    }
  }
}
  
/**
 * Implements hook_preprocess_HOOK() for page templates.
 */
function mz_staydirect_preprocess_page(&$variables) {
  global $site_variables ;
  if($site_variables && $site_variables["email"] && isset($site_variables["site_theme"])){
      // Check the value of a configuration variable.
      $config = \Drupal::config('mz_staydirect.settings');
      $site_infos = $config->get('site_variables');
      if(  $site_infos == null ){
          \Drupal::configFactory()->getEditable('mz_staydirect.settings')
          ->set('site_variables',$site_variables)
          ->save();
      }
  }
}
function mz_staydirect_preprocess_html(&$variables) {
  $service_helper = \Drupal::service('drupal.helper');
  $params = $service_helper->helper->get_parameter();
  if(isset($params['cache']) && $params['cache']==1 ){
    \Drupal::service('router.builder')->rebuild();
  }
}