<?php

/**
 * @file
 * Contains maintenance_mode_api.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function maintenance_mode_api_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mz_stripe_checkout module.
    case 'help.page.maintenance_mode_api':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('maintenance_mode_api') . '</p>';
      return $output;

    default:
  }
}
